services:
  lab-notes:
    build: .
    container_name: lab-notes
    restart: unless-stopped
    network_mode: host
    volumes:
    - lab-data:/data
    - ~/.ssh/boltz_key:/root/.ssh/boltz_key:ro
    - /home/max/.config/rclone:/root/.config/rclone:ro
    - ./static:/app/static
    environment:
    - PC_IP=192.168.1.144
    - PC_USER=max
    - PC_MAC=d8:43:ae:91:2f:9b
    - TODO_API_URL=http://todo:3000
    - OPENCLONING_URL=https://cloning.maxemanuelrichardson.beer
  opencloning:
    image: manulera/opencloning:latest
    container_name: opencloning
    ports:
    - 8001:8000
    environment:
    - ALLOWED_ORIGINS=https://lab-notes.maxemanuelrichardson.beer,https://cloning.maxemanuelrichardson.beer
    restart: unless-stopped
volumes:
  lab-data: null
